/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IcmcCore } from "../IcmcCore";

export class IcmcCore__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IcmcCore {
    return new Contract(address, _abi, signerOrProvider) as IcmcCore;
  }
}

const _abi = [
  {
    inputs: [],
    name: "getAlice",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getBob",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_alice",
        type: "address",
      },
      {
        internalType: "address",
        name: "_bob",
        type: "address",
      },
    ],
    name: "setup",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
