/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TestChannelInterface extends ethers.utils.Interface {
  functions: {
    "defundChannel(tuple,address[],uint256[])": FunctionFragment;
    "defundTransfer(tuple,bytes,bytes,bytes)": FunctionFragment;
    "depositAlice(address,uint256)": FunctionFragment;
    "disputeChannel(tuple,bytes,bytes)": FunctionFragment;
    "disputeTransfer(tuple,bytes32[])": FunctionFragment;
    "exit(address,address,address)": FunctionFragment;
    "getAlice()": FunctionFragment;
    "getBob()": FunctionFragment;
    "getChannelDispute()": FunctionFragment;
    "getDefundNonce(address)": FunctionFragment;
    "getExitableAmount(address,address)": FunctionFragment;
    "getTotalDepositsAlice(address)": FunctionFragment;
    "getTotalDepositsBob(address)": FunctionFragment;
    "getTotalTransferred(address)": FunctionFragment;
    "getTransferDispute(bytes32)": FunctionFragment;
    "getWithdrawalTransactionRecord(tuple)": FunctionFragment;
    "lock()": FunctionFragment;
    "setup(address,address)": FunctionFragment;
    "testMakeBalanceExitable(address,tuple)": FunctionFragment;
    "testMakeExitable(address,address,uint256)": FunctionFragment;
    "withdraw(tuple,bytes,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "defundChannel",
    values: [
      {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      string[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "defundTransfer",
    values: [
      {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositAlice",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeChannel",
    values: [
      {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTransfer",
    values: [
      {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "exit",
    values: [string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "getAlice", values?: undefined): string;
  encodeFunctionData(functionFragment: "getBob", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getChannelDispute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDefundNonce",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getExitableAmount",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDepositsAlice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDepositsBob",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalTransferred",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferDispute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawalTransactionRecord",
    values: [
      {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "lock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setup",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "testMakeBalanceExitable",
    values: [
      string,
      { amount: [BigNumberish, BigNumberish]; to: [string, string] }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "testMakeExitable",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [
      {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "defundChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defundTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositAlice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAlice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getChannelDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDefundNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExitableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDepositsAlice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDepositsBob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTransferred",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransferDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawalTransactionRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testMakeBalanceExitable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testMakeExitable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "AliceDeposited(address,uint256)": EventFragment;
    "ChannelDefunded(address,tuple,tuple,address[])": EventFragment;
    "ChannelDisputed(address,tuple,tuple)": EventFragment;
    "TransferDefunded(address,tuple,tuple,bytes,bytes,tuple)": EventFragment;
    "TransferDisputed(address,tuple,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AliceDeposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChannelDefunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChannelDisputed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferDefunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferDisputed"): EventFragment;
}

export class TestChannel extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TestChannelInterface;

  functions: {
    defundChannel(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      assetIds: string[],
      indices: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "defundChannel(tuple,address[],uint256[])"(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      assetIds: string[],
      indices: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    defundTransfer(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      encodedInitialTransferState: BytesLike,
      encodedTransferResolver: BytesLike,
      responderSignature: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "defundTransfer(tuple,bytes,bytes,bytes)"(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      encodedInitialTransferState: BytesLike,
      encodedTransferResolver: BytesLike,
      responderSignature: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    depositAlice(
      assetId: string,
      amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "depositAlice(address,uint256)"(
      assetId: string,
      amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    disputeChannel(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "disputeChannel(tuple,bytes,bytes)"(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    disputeTransfer(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      merkleProofData: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "disputeTransfer(tuple,bytes32[])"(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      merkleProofData: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    exit(
      assetId: string,
      owner: string,
      recipient: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "exit(address,address,address)"(
      assetId: string,
      owner: string,
      recipient: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getAlice(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getAlice()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getBob(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getBob()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getChannelDispute(
      overrides?: CallOverrides
    ): Promise<{
      0: {
        channelStateHash: string;
        nonce: BigNumber;
        merkleRoot: string;
        consensusExpiry: BigNumber;
        defundExpiry: BigNumber;
        0: string;
        1: BigNumber;
        2: string;
        3: BigNumber;
        4: BigNumber;
      };
    }>;

    "getChannelDispute()"(
      overrides?: CallOverrides
    ): Promise<{
      0: {
        channelStateHash: string;
        nonce: BigNumber;
        merkleRoot: string;
        consensusExpiry: BigNumber;
        defundExpiry: BigNumber;
        0: string;
        1: BigNumber;
        2: string;
        3: BigNumber;
        4: BigNumber;
      };
    }>;

    getDefundNonce(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getDefundNonce(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getExitableAmount(
      assetId: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getExitableAmount(address,address)"(
      assetId: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getTotalDepositsAlice(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getTotalDepositsAlice(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getTotalDepositsBob(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getTotalDepositsBob(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getTotalTransferred(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getTotalTransferred(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    getTransferDispute(
      transferId: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        transferStateHash: string;
        transferDisputeExpiry: BigNumber;
        isDefunded: boolean;
        0: string;
        1: BigNumber;
        2: boolean;
      };
    }>;

    "getTransferDispute(bytes32)"(
      transferId: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        transferStateHash: string;
        transferDisputeExpiry: BigNumber;
        isDefunded: boolean;
        0: string;
        1: BigNumber;
        2: boolean;
      };
    }>;

    getWithdrawalTransactionRecord(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "getWithdrawalTransactionRecord(tuple)"(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    lock(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "lock()"(
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    setup(
      _alice: string,
      _bob: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setup(address,address)"(
      _alice: string,
      _bob: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    testMakeBalanceExitable(
      assetId: string,
      balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "testMakeBalanceExitable(address,tuple)"(
      assetId: string,
      balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    testMakeExitable(
      assetId: string,
      recipient: string,
      maxAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "testMakeExitable(address,address,uint256)"(
      assetId: string,
      recipient: string,
      maxAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdraw(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdraw(tuple,bytes,bytes)"(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  defundChannel(
    ccs: {
      channelAddress: string;
      alice: string;
      bob: string;
      assetIds: string[];
      balances: {
        amount: [BigNumberish, BigNumberish];
        to: [string, string];
      }[];
      processedDepositsA: BigNumberish[];
      processedDepositsB: BigNumberish[];
      defundNonces: BigNumberish[];
      timeout: BigNumberish;
      nonce: BigNumberish;
      merkleRoot: BytesLike;
    },
    assetIds: string[],
    indices: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "defundChannel(tuple,address[],uint256[])"(
    ccs: {
      channelAddress: string;
      alice: string;
      bob: string;
      assetIds: string[];
      balances: {
        amount: [BigNumberish, BigNumberish];
        to: [string, string];
      }[];
      processedDepositsA: BigNumberish[];
      processedDepositsB: BigNumberish[];
      defundNonces: BigNumberish[];
      timeout: BigNumberish;
      nonce: BigNumberish;
      merkleRoot: BytesLike;
    },
    assetIds: string[],
    indices: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  defundTransfer(
    cts: {
      channelAddress: string;
      transferId: BytesLike;
      transferDefinition: string;
      initiator: string;
      responder: string;
      assetId: string;
      balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
      transferTimeout: BigNumberish;
      initialStateHash: BytesLike;
    },
    encodedInitialTransferState: BytesLike,
    encodedTransferResolver: BytesLike,
    responderSignature: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "defundTransfer(tuple,bytes,bytes,bytes)"(
    cts: {
      channelAddress: string;
      transferId: BytesLike;
      transferDefinition: string;
      initiator: string;
      responder: string;
      assetId: string;
      balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
      transferTimeout: BigNumberish;
      initialStateHash: BytesLike;
    },
    encodedInitialTransferState: BytesLike,
    encodedTransferResolver: BytesLike,
    responderSignature: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  depositAlice(
    assetId: string,
    amount: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "depositAlice(address,uint256)"(
    assetId: string,
    amount: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  disputeChannel(
    ccs: {
      channelAddress: string;
      alice: string;
      bob: string;
      assetIds: string[];
      balances: {
        amount: [BigNumberish, BigNumberish];
        to: [string, string];
      }[];
      processedDepositsA: BigNumberish[];
      processedDepositsB: BigNumberish[];
      defundNonces: BigNumberish[];
      timeout: BigNumberish;
      nonce: BigNumberish;
      merkleRoot: BytesLike;
    },
    aliceSignature: BytesLike,
    bobSignature: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "disputeChannel(tuple,bytes,bytes)"(
    ccs: {
      channelAddress: string;
      alice: string;
      bob: string;
      assetIds: string[];
      balances: {
        amount: [BigNumberish, BigNumberish];
        to: [string, string];
      }[];
      processedDepositsA: BigNumberish[];
      processedDepositsB: BigNumberish[];
      defundNonces: BigNumberish[];
      timeout: BigNumberish;
      nonce: BigNumberish;
      merkleRoot: BytesLike;
    },
    aliceSignature: BytesLike,
    bobSignature: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  disputeTransfer(
    cts: {
      channelAddress: string;
      transferId: BytesLike;
      transferDefinition: string;
      initiator: string;
      responder: string;
      assetId: string;
      balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
      transferTimeout: BigNumberish;
      initialStateHash: BytesLike;
    },
    merkleProofData: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "disputeTransfer(tuple,bytes32[])"(
    cts: {
      channelAddress: string;
      transferId: BytesLike;
      transferDefinition: string;
      initiator: string;
      responder: string;
      assetId: string;
      balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
      transferTimeout: BigNumberish;
      initialStateHash: BytesLike;
    },
    merkleProofData: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  exit(
    assetId: string,
    owner: string,
    recipient: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "exit(address,address,address)"(
    assetId: string,
    owner: string,
    recipient: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getAlice(overrides?: CallOverrides): Promise<string>;

  "getAlice()"(overrides?: CallOverrides): Promise<string>;

  getBob(overrides?: CallOverrides): Promise<string>;

  "getBob()"(overrides?: CallOverrides): Promise<string>;

  getChannelDispute(
    overrides?: CallOverrides
  ): Promise<{
    channelStateHash: string;
    nonce: BigNumber;
    merkleRoot: string;
    consensusExpiry: BigNumber;
    defundExpiry: BigNumber;
    0: string;
    1: BigNumber;
    2: string;
    3: BigNumber;
    4: BigNumber;
  }>;

  "getChannelDispute()"(
    overrides?: CallOverrides
  ): Promise<{
    channelStateHash: string;
    nonce: BigNumber;
    merkleRoot: string;
    consensusExpiry: BigNumber;
    defundExpiry: BigNumber;
    0: string;
    1: BigNumber;
    2: string;
    3: BigNumber;
    4: BigNumber;
  }>;

  getDefundNonce(
    assetId: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getDefundNonce(address)"(
    assetId: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getExitableAmount(
    assetId: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getExitableAmount(address,address)"(
    assetId: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTotalDepositsAlice(
    assetId: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getTotalDepositsAlice(address)"(
    assetId: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTotalDepositsBob(
    assetId: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getTotalDepositsBob(address)"(
    assetId: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTotalTransferred(
    assetId: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getTotalTransferred(address)"(
    assetId: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTransferDispute(
    transferId: BytesLike,
    overrides?: CallOverrides
  ): Promise<{
    transferStateHash: string;
    transferDisputeExpiry: BigNumber;
    isDefunded: boolean;
    0: string;
    1: BigNumber;
    2: boolean;
  }>;

  "getTransferDispute(bytes32)"(
    transferId: BytesLike,
    overrides?: CallOverrides
  ): Promise<{
    transferStateHash: string;
    transferDisputeExpiry: BigNumber;
    isDefunded: boolean;
    0: string;
    1: BigNumber;
    2: boolean;
  }>;

  getWithdrawalTransactionRecord(
    wd: {
      channelAddress: string;
      assetId: string;
      recipient: string;
      amount: BigNumberish;
      nonce: BigNumberish;
      callTo: string;
      callData: BytesLike;
    },
    overrides?: CallOverrides
  ): Promise<boolean>;

  "getWithdrawalTransactionRecord(tuple)"(
    wd: {
      channelAddress: string;
      assetId: string;
      recipient: string;
      amount: BigNumberish;
      nonce: BigNumberish;
      callTo: string;
      callData: BytesLike;
    },
    overrides?: CallOverrides
  ): Promise<boolean>;

  lock(overrides?: CallOverrides): Promise<BigNumber>;

  "lock()"(overrides?: CallOverrides): Promise<BigNumber>;

  setup(
    _alice: string,
    _bob: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setup(address,address)"(
    _alice: string,
    _bob: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  testMakeBalanceExitable(
    assetId: string,
    balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "testMakeBalanceExitable(address,tuple)"(
    assetId: string,
    balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  testMakeExitable(
    assetId: string,
    recipient: string,
    maxAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "testMakeExitable(address,address,uint256)"(
    assetId: string,
    recipient: string,
    maxAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdraw(
    wd: {
      channelAddress: string;
      assetId: string;
      recipient: string;
      amount: BigNumberish;
      nonce: BigNumberish;
      callTo: string;
      callData: BytesLike;
    },
    aliceSignature: BytesLike,
    bobSignature: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdraw(tuple,bytes,bytes)"(
    wd: {
      channelAddress: string;
      assetId: string;
      recipient: string;
      amount: BigNumberish;
      nonce: BigNumberish;
      callTo: string;
      callData: BytesLike;
    },
    aliceSignature: BytesLike,
    bobSignature: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    defundChannel(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      assetIds: string[],
      indices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "defundChannel(tuple,address[],uint256[])"(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      assetIds: string[],
      indices: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    defundTransfer(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      encodedInitialTransferState: BytesLike,
      encodedTransferResolver: BytesLike,
      responderSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "defundTransfer(tuple,bytes,bytes,bytes)"(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      encodedInitialTransferState: BytesLike,
      encodedTransferResolver: BytesLike,
      responderSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    depositAlice(
      assetId: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "depositAlice(address,uint256)"(
      assetId: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    disputeChannel(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "disputeChannel(tuple,bytes,bytes)"(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    disputeTransfer(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      merkleProofData: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "disputeTransfer(tuple,bytes32[])"(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      merkleProofData: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    exit(
      assetId: string,
      owner: string,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "exit(address,address,address)"(
      assetId: string,
      owner: string,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getAlice(overrides?: CallOverrides): Promise<string>;

    "getAlice()"(overrides?: CallOverrides): Promise<string>;

    getBob(overrides?: CallOverrides): Promise<string>;

    "getBob()"(overrides?: CallOverrides): Promise<string>;

    getChannelDispute(
      overrides?: CallOverrides
    ): Promise<{
      channelStateHash: string;
      nonce: BigNumber;
      merkleRoot: string;
      consensusExpiry: BigNumber;
      defundExpiry: BigNumber;
      0: string;
      1: BigNumber;
      2: string;
      3: BigNumber;
      4: BigNumber;
    }>;

    "getChannelDispute()"(
      overrides?: CallOverrides
    ): Promise<{
      channelStateHash: string;
      nonce: BigNumber;
      merkleRoot: string;
      consensusExpiry: BigNumber;
      defundExpiry: BigNumber;
      0: string;
      1: BigNumber;
      2: string;
      3: BigNumber;
      4: BigNumber;
    }>;

    getDefundNonce(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getDefundNonce(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getExitableAmount(
      assetId: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getExitableAmount(address,address)"(
      assetId: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalDepositsAlice(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTotalDepositsAlice(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalDepositsBob(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTotalDepositsBob(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalTransferred(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTotalTransferred(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTransferDispute(
      transferId: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      transferStateHash: string;
      transferDisputeExpiry: BigNumber;
      isDefunded: boolean;
      0: string;
      1: BigNumber;
      2: boolean;
    }>;

    "getTransferDispute(bytes32)"(
      transferId: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      transferStateHash: string;
      transferDisputeExpiry: BigNumber;
      isDefunded: boolean;
      0: string;
      1: BigNumber;
      2: boolean;
    }>;

    getWithdrawalTransactionRecord(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<boolean>;

    "getWithdrawalTransactionRecord(tuple)"(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<boolean>;

    lock(overrides?: CallOverrides): Promise<BigNumber>;

    "lock()"(overrides?: CallOverrides): Promise<BigNumber>;

    setup(
      _alice: string,
      _bob: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setup(address,address)"(
      _alice: string,
      _bob: string,
      overrides?: CallOverrides
    ): Promise<void>;

    testMakeBalanceExitable(
      assetId: string,
      balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] },
      overrides?: CallOverrides
    ): Promise<void>;

    "testMakeBalanceExitable(address,tuple)"(
      assetId: string,
      balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] },
      overrides?: CallOverrides
    ): Promise<void>;

    testMakeExitable(
      assetId: string,
      recipient: string,
      maxAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "testMakeExitable(address,address,uint256)"(
      assetId: string,
      recipient: string,
      maxAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdraw(tuple,bytes,bytes)"(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AliceDeposited(assetId: null, amount: null): EventFilter;

    ChannelDefunded(
      defunder: null,
      state: null,
      dispute: null,
      assetIds: null
    ): EventFilter;

    ChannelDisputed(disputer: null, state: null, dispute: null): EventFilter;

    TransferDefunded(
      defunder: null,
      state: null,
      dispute: null,
      encodedInitialState: null,
      encodedResolver: null,
      balance: null
    ): EventFilter;

    TransferDisputed(disputer: null, state: null, dispute: null): EventFilter;
  };

  estimateGas: {
    defundChannel(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      assetIds: string[],
      indices: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "defundChannel(tuple,address[],uint256[])"(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      assetIds: string[],
      indices: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    defundTransfer(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      encodedInitialTransferState: BytesLike,
      encodedTransferResolver: BytesLike,
      responderSignature: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "defundTransfer(tuple,bytes,bytes,bytes)"(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      encodedInitialTransferState: BytesLike,
      encodedTransferResolver: BytesLike,
      responderSignature: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    depositAlice(
      assetId: string,
      amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "depositAlice(address,uint256)"(
      assetId: string,
      amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    disputeChannel(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "disputeChannel(tuple,bytes,bytes)"(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    disputeTransfer(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      merkleProofData: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "disputeTransfer(tuple,bytes32[])"(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      merkleProofData: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    exit(
      assetId: string,
      owner: string,
      recipient: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "exit(address,address,address)"(
      assetId: string,
      owner: string,
      recipient: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getAlice(overrides?: CallOverrides): Promise<BigNumber>;

    "getAlice()"(overrides?: CallOverrides): Promise<BigNumber>;

    getBob(overrides?: CallOverrides): Promise<BigNumber>;

    "getBob()"(overrides?: CallOverrides): Promise<BigNumber>;

    getChannelDispute(overrides?: CallOverrides): Promise<BigNumber>;

    "getChannelDispute()"(overrides?: CallOverrides): Promise<BigNumber>;

    getDefundNonce(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getDefundNonce(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getExitableAmount(
      assetId: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getExitableAmount(address,address)"(
      assetId: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalDepositsAlice(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTotalDepositsAlice(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalDepositsBob(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTotalDepositsBob(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalTransferred(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTotalTransferred(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTransferDispute(
      transferId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTransferDispute(bytes32)"(
      transferId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWithdrawalTransactionRecord(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getWithdrawalTransactionRecord(tuple)"(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lock(overrides?: CallOverrides): Promise<BigNumber>;

    "lock()"(overrides?: CallOverrides): Promise<BigNumber>;

    setup(
      _alice: string,
      _bob: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setup(address,address)"(
      _alice: string,
      _bob: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    testMakeBalanceExitable(
      assetId: string,
      balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "testMakeBalanceExitable(address,tuple)"(
      assetId: string,
      balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] },
      overrides?: Overrides
    ): Promise<BigNumber>;

    testMakeExitable(
      assetId: string,
      recipient: string,
      maxAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "testMakeExitable(address,address,uint256)"(
      assetId: string,
      recipient: string,
      maxAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    withdraw(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdraw(tuple,bytes,bytes)"(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    defundChannel(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      assetIds: string[],
      indices: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "defundChannel(tuple,address[],uint256[])"(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      assetIds: string[],
      indices: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    defundTransfer(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      encodedInitialTransferState: BytesLike,
      encodedTransferResolver: BytesLike,
      responderSignature: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "defundTransfer(tuple,bytes,bytes,bytes)"(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      encodedInitialTransferState: BytesLike,
      encodedTransferResolver: BytesLike,
      responderSignature: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    depositAlice(
      assetId: string,
      amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "depositAlice(address,uint256)"(
      assetId: string,
      amount: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    disputeChannel(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "disputeChannel(tuple,bytes,bytes)"(
      ccs: {
        channelAddress: string;
        alice: string;
        bob: string;
        assetIds: string[];
        balances: {
          amount: [BigNumberish, BigNumberish];
          to: [string, string];
        }[];
        processedDepositsA: BigNumberish[];
        processedDepositsB: BigNumberish[];
        defundNonces: BigNumberish[];
        timeout: BigNumberish;
        nonce: BigNumberish;
        merkleRoot: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    disputeTransfer(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      merkleProofData: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "disputeTransfer(tuple,bytes32[])"(
      cts: {
        channelAddress: string;
        transferId: BytesLike;
        transferDefinition: string;
        initiator: string;
        responder: string;
        assetId: string;
        balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] };
        transferTimeout: BigNumberish;
        initialStateHash: BytesLike;
      },
      merkleProofData: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    exit(
      assetId: string,
      owner: string,
      recipient: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "exit(address,address,address)"(
      assetId: string,
      owner: string,
      recipient: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getAlice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getAlice()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBob(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getBob()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getChannelDispute(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getChannelDispute()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDefundNonce(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getDefundNonce(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getExitableAmount(
      assetId: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getExitableAmount(address,address)"(
      assetId: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalDepositsAlice(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTotalDepositsAlice(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalDepositsBob(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTotalDepositsBob(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalTransferred(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTotalTransferred(address)"(
      assetId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTransferDispute(
      transferId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTransferDispute(bytes32)"(
      transferId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWithdrawalTransactionRecord(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getWithdrawalTransactionRecord(tuple)"(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lock()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setup(
      _alice: string,
      _bob: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setup(address,address)"(
      _alice: string,
      _bob: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    testMakeBalanceExitable(
      assetId: string,
      balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "testMakeBalanceExitable(address,tuple)"(
      assetId: string,
      balance: { amount: [BigNumberish, BigNumberish]; to: [string, string] },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    testMakeExitable(
      assetId: string,
      recipient: string,
      maxAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "testMakeExitable(address,address,uint256)"(
      assetId: string,
      recipient: string,
      maxAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdraw(tuple,bytes,bytes)"(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      aliceSignature: BytesLike,
      bobSignature: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
