/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface WithdrawHelperInterface extends ethers.utils.Interface {
  functions: {
    "execute(tuple,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "execute",
    values: [
      {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;

  events: {};
}

export class WithdrawHelper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: WithdrawHelperInterface;

  functions: {
    execute(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      actualAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "execute(tuple,uint256)"(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      actualAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  execute(
    wd: {
      channelAddress: string;
      assetId: string;
      recipient: string;
      amount: BigNumberish;
      nonce: BigNumberish;
      callTo: string;
      callData: BytesLike;
    },
    actualAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "execute(tuple,uint256)"(
    wd: {
      channelAddress: string;
      assetId: string;
      recipient: string;
      amount: BigNumberish;
      nonce: BigNumberish;
      callTo: string;
      callData: BytesLike;
    },
    actualAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    execute(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      actualAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "execute(tuple,uint256)"(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      actualAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    execute(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      actualAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "execute(tuple,uint256)"(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      actualAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    execute(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      actualAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "execute(tuple,uint256)"(
      wd: {
        channelAddress: string;
        assetId: string;
        recipient: string;
        amount: BigNumberish;
        nonce: BigNumberish;
        callTo: string;
        callData: BytesLike;
      },
      actualAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
